# Pytorch Basic

해당 repository 및 code들은 wikidocs에서 제공하는 'Pytorch로 시작하는 딥 러닝 입문'을 참고하였음을 밝힙니다. 해당 자료를 바탕으로 숙지한 개념과 추가적인 저의 생각을 기록할 계획입니다. 출처는 다음 사이트와 같습니다.<br><br>
* https://wikidocs.net/book/2788

# 01. 파이토치 패키지의 기본 구성

1. torch: 메인 네임스페이스. 텐서 등의 다양한 수학 함수가 포함되어져 있으며 Numpy와 유사한 구조를 가집니다.<br><br>
2. torch.autograd: 자동 미분을 위한 함수들.<br>
ex) 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function'<br><br>
3. torch.nn: 신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의<br>
ex) RNN, LSTM과 같은 레이어, ReLU와 같은 활성화함수, MSELoss와 같은 손실 함수<br><br>
4. torch.optim: 확률적 경사 하강법(Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘이 구현<br><br>
5. torch.utils.data: SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함<br><br>
6. torch.onnx: ONNX(Opne Neural Network Exchange)의 포맷으로 모델을 export 할 때 사용. 서로 다른 딥러닝 프레임워크간에 모델을 공유할 때 사용하는 포맷


# 02. 텐서 조작하기(Tensor Manipulation) 1

### 3D Tensor(Typical Computer Vision) - 비전 분야에서의 3차원 텐서

|t| = (batch size, width, height)<br>
<img src="https://i.imgur.com/SQh8YYS.png">

### 3D Tensor(Typical Natural Language Processing) - NLP 분야에서의 3차원 텐서

|t| = (batch size, length, dim)<br>
|t| = (batch size, 문장 길이, 단어 벡터의 차원)<br>
<img src="https://i.imgur.com/uSjPkhP.png">

이는 해결하고자 하는 문제에 따라 tensor가 가지고 있는 각 dimension의 정의를 다르게 해석할 수 있음을 의미한다.

### 넘파이로 텐서 만들기(벡터와 행렬 만들기)

흔히 아래와 같이 numpy를 정의할 때 원소값들에 점(.)을 붙인다. 이는 각 원소값들의 type이 int가 아닌 float로 선언하여 부동소수점연산을 원활하게 하기 위함이다. 이러한 습관을 길러놓는것이 필요하다고 생각한다.

In [0]:
import numpy as np

t = np.array([0., 1., 2., 3., 4., 5., 6.,])
# 파이썬으로 설명하면 list를 생성해서 np.array로 1차원 array로 변환함
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [0]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [0]:
print('t[0] t[1] t[-1] =', t[0],t[1],t[-1]) # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] = 0.0 1.0 6.0


In [0]:
print('t[2:5] t[4:-1] =',t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.

t[2:5] t[4:-1] = [2. 3. 4.] [4. 5.]


In [0]:
print('t[:2] t[3:] = ', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [0]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [0]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


### 파이토치 텐서 선언하기(Pytorch Tensor Allocation)

In [0]:
import torch

In [0]:
# FloatTensor이다. 대문자에 유의하도록 하자.

t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [0]:
print(t.dim())      # rank. 즉, 차원
print(t.shape)      # shape
print(t.size())     # shape

1
torch.Size([7])
torch.Size([7])


In [0]:
print(t[0], t[1], t[-1])        # 인덱스로 접근
print(t[2:5], t[4:-1])          # 슬라이싱
print(t[:2], t[3:])             # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [0]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [0]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [0]:
print(t[:,1])   # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:,1].size())    # shape

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [0]:
print(t[:, :-1])    # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### 브로드캐스팅(Broadcasting)

In [0]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [0]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [0]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


브로드캐스팅은 딥러닝 연산에서 불가피하게 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행할 필요가 있는 경우 필요한 기능이라고 한다. 하지만 자신이 설계한 텐서들이 다른 shape이지만 같다고 착각할 때 코드는 오류를 출력하지 않으므로 수정이 어렵다. 즉, 사용자 입장에서 굉장히 조심스럽게 사용해야 하는 기능이라고 생각한다.

In [0]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


행렬 곱셈이 아니라 element-wise 곱셈이라는 것이 존재합니다. 이는 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것을 말합니다. 아래는 서로 다른 크기의 행렬이 브로드캐스팅이 된 후에 element-wise 곱셈이 수행되는 것을 보여줍니다. 이는 * 또는 mul()을 통해 수행합니다.

In [0]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


m1 행렬의 크기는 (2,2)이었습니다. m2 행렬의 크기는 (2,1)였습니다. 이 때 element-wise 곱셈을 수행하면, 두 행렬의 크기는 브로드캐스팅이 된 후에 곱셈이 수행됩니다. 더 정확히는 여기서 m2의 크기가 변환됩니다.

In [0]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [0]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [0]:
print(t.mean())

tensor(2.5000)


In [0]:
print(t.mean(dim=0))

tensor([2., 3.])


dim=0이라는 것은 첫번째 차원을 의미합니다. 행렬에서 첫번째 차원은 '행'을 의미합니다. 그리고 인자로 dim을 준다면 해당 차원을 제거한다는 의미가 됩니다. 다시 말해 행렬에서 '열'만을 남기겠다는 의미가 됩니다. 기존 행렬의 크기는 (2,2)였지만 이를 수행하면 열의 차원만 보존되면서 (1,2)가 됩니다. 이는 (2,)와 같으며 벡터를 의미합니다.

In [0]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


(2x1)은 결국 1차원이므로 (1x2)와 같이 표현되면서 위와 같이 [1.5, 3.5]로 출력됩니다. 이번에는 dim=-1을 주는 경우를 보겠습니다. 이는 마지막 차원을 제거한다는 의미이고, 결국 열의 차원을 제거한다는 의미와 같습니다. 그러므로 위와 출력 결과가 같습니다.

In [0]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


In [0]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [0]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [0]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [0]:
print(t.max()) # Returns one value: max

tensor(4.)


In [0]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


만약 두 개를 함께 리턴받는 것이 아니라 max 또는 argmax만 리턴받고 싶다면 다음과 같이 리턴값에도 인덱스를 부여하면 됩니다. 0번 인덱스를 사용하면 max 값만 받아올 수 있고, 1번 인덱스를 사용하면 argmax 값만 받아올 수 있습니다.

In [0]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [0]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# 03. 텐서 조작하기(Tensor Manipulation) 2

### 뷰(View): 원소의 수를 유지하면서 텐서의 크기 변경

파이토치 텐서의 뷰(View)는 넘파이에서의 Reshape과 같은 역할을 합니다. Reshape라는 이름에서 알 수 있듯이, 텐서의 크기(Shape)를 변경해주는 역할을 합니다.

* View는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.
* 파이토치의 View는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

In [0]:
# FloatTensor는 list 뿐만 아니라 numpy array로도 정의 가능

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [0]:
print(ft.shape)

torch.Size([2, 2, 3])


In [0]:
print(ft.view([-1,3])) # ft라는 텐서를 (?,3)의 크기로 변경
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [0]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 스퀴즈(Squeeze): 1인 차원을 제거한다.

In [0]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [0]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 언스퀴즈(Unsqueeze): 특정 위치에 1인 차원을 추가한다.

In [0]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [0]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [0]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [0]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [0]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


* view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절합니다.

### 타입 캐스팅(Type Casting)

<img src="https://i.imgur.com/Ivx6xm5.png">

텐서에는 자료형이라는 것이 있습니다. 각 데이터형별로 정의되어져 있는데, 예를 들어 32비트의 유동 소수점은 torch.FloatTensor를, 64비트의 부호 있는 정수는 torch.LongTensor를 사용합니다. GPU 연산을 위한 자료형도 있습니다. 예를 들어 torch.cuda.FLoatTensor가 그 예입니다.<br><br>
그리고 이 자료형을 변환하는 것을 타입 캐스팅이라고 합니다.

In [0]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [0]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [0]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [0]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### 연결하기(concatenate)

In [0]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [0]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [0]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### 스택킹(Stacking)

In [0]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [0]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [0]:
# torch.cat: 여러 행렬을 한 번에 연결 가능

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [0]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### ones_like와 zeros_like: 0으로 채워진 텐서와 1로 채워진 텐서

In [0]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [0]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [0]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation(덮어쓰기 연산)

In [0]:
x = torch.FloatTensor([[1,2],[3,4]])

In [0]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


곱하기 2를 수행했지만 이를 x에다가 다시 저장하지 않았으니, 곱하기 연산을 하더라도 기존의 값 x는 변하지 않는 것이 당연합니다.<br><br>
그런데 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 합니다.

In [0]:
print(x.mul_(2,)) # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# 04. 파이썬 클래스(class)

In [0]:
result = 0

In [0]:
# 함수(function)로 덧셈기 구현하기

def add(num):
    global result
    result += num
    return result

In [0]:
print(add(3))
print(add(4))

3
7


In [0]:
# 함수(function)로 두 개의 덧셈기 구현하기

result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


In [0]:
# 클래스(class)로 덧셈기 구현하기

class Calculator:
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 초기화 함수. 이를 생성자라고 한다.
        self.result = 0

    def add(self, num): # 객체 생성 후 사용할 수 있는 함수
        self.result += num
        return self.result

In [0]:
cal1 = Calculator()

In [0]:
cal2 = Calculator()

In [0]:
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
