https://www.youtube.com/watch?v=6SF_qAd99Yg&list=PLHOsBEAyYj3xf4i20sCA5o8MgVW5sIiHD&index=8

Torch: The torch package contains data structures for multi-dimensional tensors and mathmatical operations over these are defined.

In [ ]:
import torch
import numpy as np

In [ ]:
# 초기화되지 않은 행렬
# 초기화되지 않은 행렬이 선언되었지만, 사용하기 전에는 명확히 알려진 값을 포함하고 있지는 않습니다.
# 초기화되지 않은 행렬이 생성되면 그 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타납니다.

x = torch.empty(5,4)
print(x)

tensor([[3.0385e-36, 0.0000e+00, 7.0065e-44, 6.7262e-44],
        [6.3058e-44, 6.7262e-44, 7.7071e-44, 6.3058e-44],
        [6.7262e-44, 7.2868e-44, 1.1771e-43, 6.8664e-44],
        [6.8664e-44, 8.1275e-44, 7.4269e-44, 7.0065e-44],
        [8.1275e-44, 7.0065e-44, 6.8664e-44, 6.4460e-44]])


In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2)

tensor([0., 0.])

In [ ]:
torch.rand(5,6)

tensor([[0.6061, 0.8155, 0.0737, 0.4744, 0.7857, 0.7375],
        [0.1471, 0.3474, 0.2176, 0.1270, 0.8699, 0.2114],
        [0.6249, 0.2532, 0.0316, 0.7477, 0.0340, 0.4295],
        [0.5087, 0.7457, 0.3260, 0.1277, 0.5064, 0.1635],
        [0.5393, 0.4153, 0.8092, 0.4624, 0.8972, 0.2098]])

In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [ ]:
# new_* 메소드는 크기를 받습니다.
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

# dtype을 오버라이드(Override) 합니다.
# 결과는 동일한 크기를 갖습니다.
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2706, -1.2276, -0.3935],
        [ 0.1082, -0.9616, -1.3237],
        [-0.1914, -0.1603, -0.4873],
        [ 0.5816, -0.2920, -2.2715],
        [-0.3993, -1.4270, -0.1794]])


In [ ]:
l = [13, 4]
r = np.array([4,56,7])

In [ ]:
torch.tensor(l)

tensor([13,  4])

In [ ]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [ ]:
# 행렬의 크기를 구합니다.

x.size()

torch.Size([5, 4])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.0184, 0.1998],
        [0.5841, 0.6475]])
tensor([[0.4414, 0.4748],
        [0.9902, 0.8730]])


In [ ]:
x+y

tensor([[0.4598, 0.6746],
        [1.5743, 1.5205]])

In [ ]:
torch.add(x,y)

# result = torch.empty(2,2)
# torch.add(x, y, out=result)
# print(result)

tensor([[0.4598, 0.6746],
        [1.5743, 1.5205]])

In [ ]:
y.add(x)

tensor([[0.4598, 0.6746],
        [1.5743, 1.5205]])

In [ ]:
y

tensor([[0.4414, 0.4748],
        [0.9902, 0.8730]])

In [ ]:
# inplace
y.add_(x)

tensor([[0.4598, 0.6746],
        [1.5743, 1.5205]])

In [ ]:
y

tensor([[0.4598, 0.6746],
        [1.5743, 1.5205]])

In [ ]:
y[1,1]

tensor(1.5205)

In [ ]:
y[:,1]

tensor([0.6746, 1.5205])

In [ ]:
x = torch.rand(8,8)
print(x)

tensor([[0.6018, 0.2783, 0.1883, 0.8415, 0.6378, 0.3750, 0.1103, 0.1255],
        [0.8538, 0.1470, 0.4886, 0.0238, 0.0717, 0.1030, 0.6597, 0.3500],
        [0.4697, 0.1387, 0.2017, 0.7390, 0.8171, 0.1438, 0.5371, 0.6990],
        [0.0663, 0.4046, 0.4679, 0.4184, 0.4038, 0.3543, 0.5853, 0.4183],
        [0.3572, 0.2230, 0.5528, 0.7249, 0.0312, 0.1232, 0.1271, 0.1474],
        [0.0807, 0.7435, 0.6491, 0.4645, 0.4985, 0.4636, 0.2207, 0.0242],
        [0.0794, 0.0462, 0.2328, 0.9415, 0.5259, 0.7106, 0.1616, 0.4948],
        [0.6360, 0.9328, 0.6457, 0.5409, 0.0269, 0.0303, 0.3782, 0.8244]])


In [ ]:
# FC를 위해 flatten할 때 사용

x.view(64)

tensor([0.6018, 0.2783, 0.1883, 0.8415, 0.6378, 0.3750, 0.1103, 0.1255, 0.8538,
        0.1470, 0.4886, 0.0238, 0.0717, 0.1030, 0.6597, 0.3500, 0.4697, 0.1387,
        0.2017, 0.7390, 0.8171, 0.1438, 0.5371, 0.6990, 0.0663, 0.4046, 0.4679,
        0.4184, 0.4038, 0.3543, 0.5853, 0.4183, 0.3572, 0.2230, 0.5528, 0.7249,
        0.0312, 0.1232, 0.1271, 0.1474, 0.0807, 0.7435, 0.6491, 0.4645, 0.4985,
        0.4636, 0.2207, 0.0242, 0.0794, 0.0462, 0.2328, 0.9415, 0.5259, 0.7106,
        0.1616, 0.4948, 0.6360, 0.9328, 0.6457, 0.5409, 0.0269, 0.0303, 0.3782,
        0.8244])

In [ ]:
x.view(4,16)

tensor([[0.6018, 0.2783, 0.1883, 0.8415, 0.6378, 0.3750, 0.1103, 0.1255, 0.8538,
         0.1470, 0.4886, 0.0238, 0.0717, 0.1030, 0.6597, 0.3500],
        [0.4697, 0.1387, 0.2017, 0.7390, 0.8171, 0.1438, 0.5371, 0.6990, 0.0663,
         0.4046, 0.4679, 0.4184, 0.4038, 0.3543, 0.5853, 0.4183],
        [0.3572, 0.2230, 0.5528, 0.7249, 0.0312, 0.1232, 0.1271, 0.1474, 0.0807,
         0.7435, 0.6491, 0.4645, 0.4985, 0.4636, 0.2207, 0.0242],
        [0.0794, 0.0462, 0.2328, 0.9415, 0.5259, 0.7106, 0.1616, 0.4948, 0.6360,
         0.9328, 0.6457, 0.5409, 0.0269, 0.0303, 0.3782, 0.8244]])

In [ ]:
# -1은 다른 차원들을 사용하여 유추합니다.

x.view(-1,16)   # x.view(4,16)

tensor([[0.6018, 0.2783, 0.1883, 0.8415, 0.6378, 0.3750, 0.1103, 0.1255, 0.8538,
         0.1470, 0.4886, 0.0238, 0.0717, 0.1030, 0.6597, 0.3500],
        [0.4697, 0.1387, 0.2017, 0.7390, 0.8171, 0.1438, 0.5371, 0.6990, 0.0663,
         0.4046, 0.4679, 0.4184, 0.4038, 0.3543, 0.5853, 0.4183],
        [0.3572, 0.2230, 0.5528, 0.7249, 0.0312, 0.1232, 0.1271, 0.1474, 0.0807,
         0.7435, 0.6491, 0.4645, 0.4985, 0.4636, 0.2207, 0.0242],
        [0.0794, 0.0462, 0.2328, 0.9415, 0.5259, 0.7106, 0.1616, 0.4948, 0.6360,
         0.9328, 0.6457, 0.5409, 0.0269, 0.0303, 0.3782, 0.8244]])

In [ ]:
y = x.numpy()
print(y)

[[0.60182726 0.27829528 0.1882745  0.84149855 0.6378488  0.37497723
  0.11029363 0.12548852]
 [0.85382235 0.14696938 0.48864686 0.02377862 0.07170737 0.10304266
  0.65971243 0.35001433]
 [0.46969217 0.13868755 0.20168775 0.7390265  0.8171414  0.14379883
  0.5370778  0.69901276]
 [0.06625515 0.40461153 0.46792483 0.4184081  0.40379602 0.35428375
  0.58525914 0.4183035 ]
 [0.3571959  0.22303194 0.5528485  0.7249411  0.0311718  0.1232397
  0.12706196 0.14743721]
 [0.08073962 0.743536   0.6491111  0.4645167  0.49845618 0.46364462
  0.22066247 0.02424347]
 [0.07941866 0.04623216 0.23281187 0.9415215  0.525852   0.71062475
  0.16161138 0.49478924]
 [0.6360462  0.9327562  0.6456862  0.54092425 0.02688831 0.03025752
  0.3781693  0.82441324]]


In [ ]:
type(y)

numpy.ndarray

In [ ]:
x = torch.ones(1)

In [ ]:
x

tensor([1.])

In [ ]:
# 만약 tensor에 하나의 값만 존재한다면, .item()을 사용하면 숫자 값을 얻을 수 있습니다.
# DL: loss 값을 뽑아낼 때 사용

x.item()

1.0

In [ ]:
# Numpy 배열을 Torch Tensor로 변환하기
# Numpy 배열을 변경하면 Torch Tensor의 값도 자동 변경

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# CUDA Tensor

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device``를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.
if torch.cuda.is_available():
    device = torch.device('cuda')           # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)   # GPU 상에 직접적으로 tensor를 사용하거나
    x = x.to(device)                        # ``.to('cuda')``를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))        # ``.to``는 dtype도 함께 변경합니다.

tensor([[ 0.7294, -0.2276,  0.6065],
        [ 1.1082,  0.0384, -0.3237],
        [ 0.8086,  0.8397,  0.5127],
        [ 1.5816,  0.7080, -1.2715],
        [ 0.6007, -0.4270,  0.8206]], device='cuda:0')
tensor([[ 0.7294, -0.2276,  0.6065],
        [ 1.1082,  0.0384, -0.3237],
        [ 0.8086,  0.8397,  0.5127],
        [ 1.5816,  0.7080, -1.2715],
        [ 0.6007, -0.4270,  0.8206]], dtype=torch.float64)
