https://www.youtube.com/watch?v=_4gEHlsvSZ8

In [ ]:
import torch

In [ ]:
# 변수 선언(+데이터 입력)

x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
# 모델 내 연산 예측값 산출

y = x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [ ]:
# 손실함수 계산

z = 2*y**2
res = z.mean()

In [ ]:
# 손실 산출
# 스칼라값 --> 미분의 대상

print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [ ]:
# d(res)/d(x_i) = x_i + 1
# res = (z_1 + .. + z_4)/4
# z_i = 2*y_i**2
# z_i = 2*(x_i+1)**2

res.backward()

In [ ]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


```python
import torch.nn as nn
import torch.nn.functional as F
```